FROM apify/actor-node:20

WORKDIR /usr/src/app

COPY package*.json tsconfig.json ./
RUN npm ci --include=dev

COPY src/ ./src/
RUN npm run build

RUN npm prune --omit=dev

CMD ["node", "dist/main.js"]
